name: CI for WebHelp Contribution

on:
  push:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      zowe-version:
        description: "Specify the Zowe verison"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Install Node Package Dependencies
      id: install
      run: npm i --prod

    - name: Setup zowe.json file
      id: setup
      run: |
        jq '.commandGroups=["zos-files","zos-jobs"]' zowe.template.json > zowe.json
        echo "$(jq '.profiles=["zosmf-profile", "base-profile"]' zowe.json)" > zowe.json
        npm run contribute

    - name: Get Zowe version
      id: get-version
      run: |
        curl -s https://raw.githubusercontent.com/zowe/zowe-cli-standalone-package/master/zowe-versions.yaml > __zowe__version__
        echo "::set-output name=number::$([[ $(cat __zowe__version__ | grep zowe:) != "" ]] && (cat __zowe__version__ | grep zowe: | cut -d ':' -f 2) || echo 'CLI_v'$(npx zowe --version))"
        rm __zowe__version__

    - name: Build Web Help
      id: build
      run: |
        npm run build:local -- ${{ github.event.inputs.zowe-version || steps.get-version.outputs.number }}
        npm install -g puppeteer-cli
        export margin="0.4in"
        puppeteer print ./generatedWebHelp/docs/all.html ./zowe.pdf --margin-top $margin --margin-right $margin --margin-bottom $margin --margin-left $margin --no-sandbox 

    - name: Archive Results
      id: upload
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: |
          generatedWebHelp/
          zowe.pdf
